version: '3'

services:
  ubuntu:
    build:
      context: ./ubuntu
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ../:/app
      - ../www:/var/www
    hostname: webserv
    restart: on-failure
    container_name: ubuntu
