version: '3'

services:
  debian:
    build:
      context: ./debian
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ../:/app
      - ../www:/var/www
    restart: on-failure
    container_name: debian