name: CMake Build and Test

on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GCC
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install CMake and Boost
        run: |
          sudo apt-get update
          sudo apt-get install cmake libboost-all-dev


      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Test
        run: |
          cd build
          ctest
